### ISSUE TITLE
NPE on sendEvent

### ISSUE THREAD

**Issue by Aliaksandr-Band** [spring-projects/spring-statemachine#359]
Hi, in our project I use statemachine configured with timeouts for each state. During testing I've discovered two issues and both seemed related to TimerTrigger.

 **Issue 1:** Sometimes my test for statemachine configuration may fail with NPE on `sendEvent()`. Debugging this issue I can guess that machine is stopped by TimerTrigger while `sendEvent()` works.
NPE is thrown by following code from _AbstractStateMachine.class_:
`			if (StateMachineUtils.containsAtleastOne(source.getIds(), currentState.getIds())) {
`, 
during execution `currentState `is NULL.

 I've attached archive with test which reproduces this problem. Run `StateMachineTest.testNPE()`. Also there is a _NPE.stack_.

**Issue 2:** When I've been trying to use StateMachineTestPlan with multiple test steps I've faced with deadlock problem. The reason is seemed in a way how each test step is executed. The current approach starts statemachine for each test step:
`			for (StateMachine<S, E> stateMachine : stateMachines.values()) {
				stateMachine.start();
			}
`
and in combination with TimerTrigger this leads to Threads deadlock. Also this issues is similar to #315.

 Please find attached stack traces for blocked threads _main.thread.stack_ and _ThreadPoolTaskExecutor.thread.stack_. Also you may run test to reproduce this issue `StateMachineTest.testDeadlock`. Repeate this test until problem appears.

Most of all I'm worried about NPE issue because there is chance to get it in production code.

Used StateMachine version is _1.2.3.RELEASE_.

attachments [archive.zip](https://github.com/spring-projects/spring-statemachine/files/996991/archive.zip)

Thanks.

**Comment by jvalkeal** [comment]
@Aliaksandr-Band Would you mind checking fixes I pushed for this issues and #360. If those looks ok from your point of view I could try to create a new release later this week. I'll go PTO after this week so it might be a good to create a release before that.

**Comment by Aliaksandr-Band** [comment]
Hi Janne the issue with NPE is still exists. Your fix just reduces chances to get it. My previous test for NPE doesn’t discover the issue after your fix, but my real tests are still failed. I've attached new version of test which shows the problem.
It looks like code which sets/gets `currentState` field should have common synchronization point.

Thanks.
[StateMachineNPEtest.zip](https://github.com/spring-projects/spring-statemachine/files/1001552/StateMachineNPEtest.zip)

**Comment by jvalkeal** [comment]
@Aliaksandr-Band See latest fix I did for '1.2.x`.

**Comment by Aliaksandr-Band** [comment]
@jvalkeal Tests passed. Thanks.

**Comment by jvalkeal** [comment]
Ok, think we need to do a bigger overhaul latest with 2.x as things a starting to get a bit too complex. I'll try to release this tomorrow.
